# .repo.toml

# TODO: mirrors later

[about]
description = "Watch github actions run"
topics = ["github-cli"]
license = "GPL-2.0-only"

[urls]
git_ssh = "git@github.com:fini-net/gh-observer.git"
web_url = "https://github.com/fini-net/gh-observer"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
