# .repo.toml

# TODO: mirrors later

[about]
description = "ðŸ”Ž Terminal UI for watching GitHub Actions CI/CD workflows with runtime metrics, queue times, and check status - alternative to gh pr checks --watch"
topics = ["error-logs", "gh-extension", "github-actions", "github-cli", "latency-monitor", "pull-requests", "tui-app"]
license = "GPL-2.0-only"

[urls]
git_ssh = "git@github.com:fini-net/gh-observer.git"
web_url = "https://github.com/fini-net/gh-observer"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
